##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Amplifying Black Voices in Iowa
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A CLIR supported, Melon funded grant
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Amplifying Black Voices in Iowa Project is a collaboration between 7 Institutions featureing the untold histories of the black communicty that helped to create the Iowa we know today."
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: iowa,black,african american,history,
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Iowa State University Library

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: abvi-single-site
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  
page_gen:
  - data: 'abvi-single-site'
  - data: 'institutions'
    template: 'institution'
    name: 'institutionid'
    dir: 'institutions'
    extension: 'html'
    filter: 'institutionid'  

##########
# Institituions pages
collections:
  institutions:
    output: true


##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Council on Library and Information Resources (CLIR) Grant"
organization-link: https://www.clir.org/hiddencollections/
organization-logo-banner: 
organization-logo-nav: https://www.clir.org/wp-content/uploads/sites/6/2017/10/CLIR_red_w_wordmark.jpg

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
